apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Values.service.name }}

   