name: CICD BACKEND TBSI - DEMO B STANDARD DEPLOYMENT

on:
  push:
    branches:
      - "main"

jobs:
  Build:
    runs-on: ${{ vars.RUNNER_BUILD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
   
      - name: Set environment variables  
        env:
          TBSI_SECRET: ${{ secrets.TBSI_SECRET }}
        run: |
          echo ${TBSI_SECRET} | ${{ secrets.CONVERTING_METHOD }} >> ${{ vars.WORKDIR }}/${{ vars.SECRET_FILENAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
         
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.TBSI_DOCKER }}:${{ vars.TBSI_TAGS }}${{ github.run_number }}

  Push:
    name: Push
    needs: build
    runs-on: ${{ vars.RUNNER }}
    steps:
      - name: Deploy to Kubernetes
        run: |
          helm upgrade be-tbsi-b --kubeconfig ${{ secrets.KUBE_CONFIG }} ${{ vars.TBSI_CHART }} --install --namespace=tbsi --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.TBSI_DOCKER }}:${{ vars.TBSI_TAGS }}${{ github.run_number }}


